ip_tort:
  - CAac013
  - CAha013
  - CAac005
  - CAha005
  - CAhb001
  - CAhb006
  - CAha006
  - CAhb005
  - CAhb003
  - CAhe003
  - CAhe002
  - CGjg001
  - CGag001
  - CGha004
  - CGha009
  - CGha005
  - OAha008
  - OAha004
  - OAha006
  - OAha001
  - OAhb001
  - OAhb002
  - OAab007
  - OGha001
  - OGha002
  - OGhb001
  - OGhb003
  - OGha005
  - OGab006
  - OAhc002
  - CGjg001 
  - CGag001
  - CGha004
  - CGha009
  - CGhc001
  - CGha007
  - CGha008
  - CGjh016
  - CGag001
  - CGag002

counterfeit:
  - CAac013
  - CAac005
  - CAha013
  - CAha005
  - CAhb0o1
  - Cahboo6
  - CAha006
  - CAhb005
  - CAhb003
  - CAhe003
  - CGjs001
  - CAhe002
  - CGjg001
  - CGag001
  - CGag001
  - CCha004
  - CCha004
  - CGha009
  - Ccha005
  - CCha009
  - OAha008
  - OAhb002
  - CGho001
  - OAha001
  - OAhb001
  - Ccha007
  - OAha004
  - OAha006
  - Ccha0o8
  - OAab007
  - Ocha001
  - CGjho16
  - OGha003
  - OGhb001
  - OGha002
  - OCha005
  - OGabOo6
  - OAhc002
  - OGho002

hmogenization:
  - CAdb002
  - CAie001
  - CAhd001

hormonyUX:
  - CAca013